#!/usr/bin/env python

import subprocess
import optparse


def get_args():
    parse = optparse.OptionParser()
    parse.add_option("-i", "--interface", dest="interface", help="Interface to change MAC")
    parse.add_option("-m", "--mac", dest="new_mac", help="New MAC address")
    (options, arguments) = parse.parse_args()

    if not options.interface:
        parse.error(" network interface not specified. (--help for more info.)")
    elif not options.new_mac:
        parse.error(" no MAC address entered. (--help for more info.)")
    return options


def change_mac(interface, new_mac):
    print("Changing the MAC for " + interface + " to " + new_mac)
    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", new_mac])
    subprocess.call(["ifconfig", interface, "up"])


options = get_args()
change_mac(options.interface, options.new_mac)

#takes user input with -m and -i in the terminal ie python filename.py -i interface -m MAC address
#asks again when there's no user input. throws error on wrong input
#now slightly more secure. you could give commands to the terminal via user input in the previous version
